### ISSUE TITLE
Profile Not Updated

### ISSUE THREAD

**Issue by hasancansaral** [loungeplease/loungeplease-support#5]
**Describe the bug**
When I try to change my phone number or e-mail it doesn’t change.

**To Reproduce**
1. Click profile button on the right end side of the app.
2. Go to e-mail or phone number buttons.
3. Change your e-mail or phone number and quit from the app.

**Expected behavior**
What I expect from the app is to update my phone number and e-mail address.

**Actual behavior**
It doesn’t change anything.

**Environment (please complete the following information):**
 - OS: Android
 - Version: loungeplease-mobile 2018-08-06 16-44-00.apk

**Comment by hasancansaral** [comment]
Resolved.

**Comment by aucuncu** [comment]
I still experience the same problem on the 08.10 android release.
